import os
import re
import json
import tempfile
import shutil
from typing import Dict, Any, List, Tuple


def slugify(text: str) -> str:
    t = text.lower().strip()
    t = re.sub(r"[^a-z0-9\s/_-]", "", t)
    t = t.replace("/", "-")
    t = re.sub(r"\s+", "-", t)
    t = re.sub(r"-+", "-", t)
    t = t.strip("-")
    return t or "project"


def write_file(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def scaffold_project_zip(manifest: Dict[str, Any]) -> Tuple[str, str]:
    project_name = manifest.get("project", {}).get("name", "MyApp")
    project_slug = slugify(project_name)

    tmpdir = tempfile.mkdtemp(prefix="scaffold_")
    project_dir = os.path.join(tmpdir, project_slug)
    os.makedirs(project_dir, exist_ok=True)

    # Generate files
    _generate_app(project_dir, manifest)
    _generate_api(project_dir, manifest)
    _generate_models(project_dir, manifest)
    _generate_templates(project_dir, manifest)
    _generate_static(project_dir)
    _generate_metadata(project_dir, manifest)

    # Zip
    base_name = os.path.join(tmpdir, project_slug)
    archive_path = shutil.make_archive(base_name, 'zip', tmpdir, project_slug)
    zip_name = f"{project_slug}.zip"
    return archive_path, zip_name


def _generate_metadata(project_dir: str, manifest: Dict[str, Any]):
    requirements = "Flask>=3.0.0\n"
    write_file(os.path.join(project_dir, "requirements.txt"), requirements)

    readme = f"""# {manifest['project']['name']}\n\nGenerated by the Onboarding Wizard.\n\nHow to run:\n\n1. Create virtual environment\n2. pip install -r requirements.txt\n3. python app.py\n\n"""
    write_file(os.path.join(project_dir, "README.md"), readme)

    gitignore = """__pycache__/\n.env\n.venv/\n*.pyc\n*.pyo\n*.pyd\n*.sqlite3\n.DS_Store\n.idea/\n.vscode/\n*/__pycache__/\n"""
    write_file(os.path.join(project_dir, ".gitignore"), gitignore)


def _generate_app(project_dir: str, manifest: Dict[str, Any]):
    pages = manifest.get("pages", [])
    apis = manifest.get("apis", [])

    # Build routes for pages
    routes_code = []
    for page in pages:
        name = page.get("name", "Page")
        route = page.get("route") or f"/{slugify(name)}"
        func_name = re.sub(r"[^a-z0-9_]+", "_", (slugify(name) or "page").lower())
        if route == "/":
            func_name = "home"
        routes_code.append(f"""
@app.route('{route}')
def {func_name}():
    return render_template('pages/{(slugify(name) or 'page')}.html', nav=PAGES, title='{name}')
""")

    # PAGES constant
    pages_const = json.dumps(pages, indent=2)

    app_py = f"""from flask import Flask, render_template\nfrom api.routes import api_bp\nimport os\n\napp = Flask(__name__)\napp.register_blueprint(api_bp)\n\nPAGES = {pages_const}\n\n@app.route('/health')\ndef health():\n    return {{'status': 'ok'}}\n{''.join(routes_code)}\nif __name__ == '__main__':\n    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)), debug=True)\n"""

    write_file(os.path.join(project_dir, "app.py"), app_py)


def _generate_api(project_dir: str, manifest: Dict[str, Any]):
    apis = manifest.get("apis", [])

    lines = [
        "from flask import Blueprint, jsonify, request",
        "api_bp = Blueprint('api', __name__)",
        ""
    ]

    for api in apis:
        method = (api.get("method") or "GET").upper()
        path = api.get("path") or "/api/endpoint"
        handler = api.get("handler") or f"{method.lower()}_endpoint"
        safe_handler = re.sub(r"[^a-z0-9_]", "_", handler.lower())
        lines.append(f"@api_bp.route('{path}', methods=['{method}'])")
        body = (
            "def {name}():\n"
            "    return jsonify({{'status': 'ok', 'handler': '{name}', 'method': request.method, 'path': '{path}'}})\n"
        ).format(name=safe_handler, path=path)
        lines.append(body)
        lines.append("")

    if not apis:
        # default example endpoint
        lines.append("@api_bp.route('/api/example', methods=['GET'])")
        lines.append("def get_example():\n    return jsonify({'message': 'Hello from API'})\n")

    write_file(os.path.join(project_dir, "api/__init__.py"), "")
    write_file(os.path.join(project_dir, "api/routes.py"), "\n".join(lines))


def _generate_models(project_dir: str, manifest: Dict[str, Any]):
    models = manifest.get("models", [])

    lines = ["from dataclasses import dataclass\n"]

    for model in models:
        name = model.get("name") or "Model"
        fields = model.get("fields", [])
        lines.append(f"@dataclass\nclass {re.sub(r'[^A-Za-z0-9_]', '', name.title().replace(' ', ''))}:\n")
        if fields:
            for f in fields:
                fname = re.sub(r"[^a-zA-Z0-9_]", "_", (f.get("name") or "field").lower())
                ftype = (f.get("type") or "str").strip()
                # Map simple types
                fmap = {"int": "int", "str": "str", "string": "str", "float": "float", "bool": "bool"}
                ftype_py = fmap.get(ftype.lower(), "str")
                lines.append(f"    {fname}: {ftype_py}")
        else:
            lines.append("    pass")
        lines.append("")

    if not models:
        lines.append("@dataclass\nclass Example:\n    id: int\n    name: str\n")

    write_file(os.path.join(project_dir, "models.py"), "\n".join(lines))


def _generate_templates(project_dir: str, manifest: Dict[str, Any]):
    pages = manifest.get("pages", [])

    base_html = """<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n  <title>{{ title or 'App' }}</title>\n  <link rel=\"stylesheet\" href=\"/static/style.css\" />\n</head>\n<body>\n  <nav class=\"nav\">\n    <a class=\"brand\" href=\"/\">{{ (title or 'App')[:1] }}</a>\n    {% if nav %}\n    {% for p in nav %}\n      <a href=\"{{ p.route }}\">{{ p.name }}</a>\n    {% endfor %}\n    {% endif %}\n  </nav>\n  <main class=\"container\">\n    {% block content %}{% endblock %}\n  </main>\n</body>\n</html>\n"""

    write_file(os.path.join(project_dir, "templates/base.html"), base_html)

    if not pages:
        pages = [{"name": "Home", "route": "/"}]

    for page in pages:
        name = page.get("name") or "Page"
        fname = (re.sub(r"[^a-z0-9_-]", "-", name.lower()) or "page") + ".html"
        content = f"""{{% extends 'base.html' %}}\n{{% block content %}}\n<h1>{name}</h1>\n<p>This is the {name} page.</p>\n{{% endblock %}}\n"""
        write_file(os.path.join(project_dir, f"templates/pages/{fname}"), content)


def _generate_static(project_dir: str):
    css = """:root {\n  --bg: #0b1021;\n  --fg: #e6e6e6;\n  --muted: #9aa4b2;\n  --accent: #5b8cff;\n}\n* { box-sizing: border-box; }\nbody {\n  margin: 0;\n  font-family: -apple-system, system-ui, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, 'Apple Color Emoji', 'Segoe UI Emoji';\n  background: var(--bg);\n  color: var(--fg);\n}\n.nav {\n  display: flex;\n  gap: 1rem;\n  align-items: center;\n  padding: 0.75rem 1rem;\n  border-bottom: 1px solid #1c2340;\n  position: sticky;\n  top: 0;\n  background: rgba(11,16,33,0.8);\n  backdrop-filter: blur(6px);\n}\n.nav a { color: var(--fg); text-decoration: none; opacity: 0.9; }\n.nav a:hover { color: var(--accent); }\n.nav .brand {\n  font-weight: 800;\n  width: 32px; height: 32px; border-radius: 8px;\n  background: linear-gradient(135deg, #5b8cff, #7a5bff);\n  color: white; display: grid; place-items: center;\n}\n.container {\n  max-width: 900px;\n  margin: 2rem auto;\n  padding: 0 1rem;\n}\n"""
    write_file(os.path.join(project_dir, "static/style.css"), css)

