import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import uuid
from flask import Flask, render_template, request, jsonify, send_file, abort
from io import BytesIO
import zipfile
from generator import generate_mockup, build_full_page

app = Flask(__name__)

STORE = {}

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/generate", methods=["POST"]) 
def api_generate():
    data = request.get_json(silent=True) or {}
    idea = data.get("idea") or request.form.get("idea")
    if not idea or not idea.strip():
        return jsonify({"error": "Missing 'idea' text"}), 400

    result = generate_mockup(idea)
    mockup_id = str(uuid.uuid4())
    STORE[mockup_id] = result

    return jsonify({
        "id": mockup_id,
        "title": result["title"],
        "components": result["components"],
        "html": result["html"],
        "css": result["css"],
        "js": result["js"]
    })

@app.route("/mockup/<mockup_id>")
def mockup_page(mockup_id):
    result = STORE.get(mockup_id)
    if not result:
        abort(404)
    full = build_full_page(result["title"], result["html"], result["css"], result["js"])
    return full

@app.route("/api/mockup/<mockup_id>")
def api_mockup(mockup_id):
    result = STORE.get(mockup_id)
    if not result:
        return jsonify({"error": "Not found"}), 404
    return jsonify({
        "id": mockup_id,
        "title": result["title"],
        "components": result["components"],
        "html": result["html"],
        "css": result["css"],
        "js": result["js"]
    })

@app.route("/download/<mockup_id>")
def download_zip(mockup_id):
    result = STORE.get(mockup_id)
    if not result:
        abort(404)

    # Build exportable files
    title = result["title"]
    html_body = result["html"]
    css = result["css"]
    js = result["js"]

    index_html = f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\"> 
  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"> 
  <title>{title}</title>
  <link rel=\"stylesheet\" href=\"styles.css\">
</head>
<body>
{html_body}
<script src=\"script.js\"></script>
</body>
</html>
"""

    mem = BytesIO()
    with zipfile.ZipFile(mem, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("index.html", index_html)
        zf.writestr("styles.css", css)
        zf.writestr("script.js", js)
        zf.writestr("README.txt", "Generated by figmahtml-mockup-generator-from-idea-text\nOpen index.html in your browser.\n")
    mem.seek(0)

    return send_file(mem, as_attachment=True, download_name=f"mockup_{mockup_id}.zip", mimetype="application/zip")

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)



def create_app():
    return app


@app.route('/health', methods=['GET'])
def _auto_stub_health():
    return 'Auto-generated stub for /health', 200
