from io import BytesIO
from typing import Dict, Any, List
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    ListFlowable,
    ListItem,
    PageBreak,
)

from .utils import format_currency, percent


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="SectionHeader", parent=styles["Heading2"], spaceBefore=12, spaceAfter=6))
    styles.add(ParagraphStyle(name="Small", parent=styles["Normal"], fontSize=9, leading=12))
    styles.add(ParagraphStyle(name="Meta", parent=styles["Normal"], textColor=colors.grey, fontSize=9))
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)
    # Footer line
    canvas.line(15 * mm, 15 * mm, w - 15 * mm, 15 * mm)
    # Page number
    page_num = canvas.getPageNumber()
    canvas.drawRightString(w - 15 * mm, 10 * mm, f"Page {page_num}")
    canvas.restoreState()


def _p(text: str, style) -> Paragraph:
    return Paragraph(escape(text or ""), style)


def _bullet_list(items: List[str], style_normal) -> ListFlowable:
    list_items = [ListItem(_p(str(i), style_normal), leftIndent=12) for i in items if str(i).strip()]
    return ListFlowable(list_items, bulletType="bullet", start="-", leftIndent=18)


def build_pdf_report(data: Dict[str, Any]) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=f"{data.get('project', {}).get('name', 'Project Report')} - Analysis Report",
        author=data.get("generated_by") or "System",
        subject="Project Analysis Report",
    )

    styles = _styles()
    story = []

    project = data.get("project", {})
    analysis = data.get("analysis", {})
    metrics = analysis.get("metrics", {})
    timeline = project.get("timeline", {})

    # Title
    story.append(Paragraph(escape(project.get("name", "Project Report")), styles["Title"]))
    story.append(Spacer(1, 6))
    meta_text = (
        f"Generated for: {escape(str(data.get('generated_for') or 'Stakeholders'))} | "
        f"Generated by: {escape(str(data.get('generated_by') or 'System'))} | "
        f"Generated at: {escape(str(data.get('generated_at') or ''))}"
    )
    story.append(Paragraph(meta_text, styles["Meta"]))
    story.append(Spacer(1, 12))

    # Project Overview
    story.append(Paragraph("Project Overview", styles["SectionHeader"]))
    overview_tbl = [
        ["Owner", project.get("owner") or "-"],
        ["Status", project.get("status") or "-"],
        ["Stakeholders", ", ".join(project.get("stakeholders") or []) or "-"],
        ["Start Date", timeline.get("start_date") or "-"],
        ["End Date", timeline.get("end_date") or "-"],
    ]
    t = Table(overview_tbl, colWidths=[35 * mm, None])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("BOX", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )
    story.append(t)
    if project.get("description"):
        story.append(Spacer(1, 8))
        story.append(Paragraph("Description", styles["Heading3"]))
        story.append(_p(project.get("description", ""), styles["Normal"]))
    story.append(Spacer(1, 12))

    # Timeline / Milestones
    milestones = timeline.get("milestones") or []
    if milestones:
        story.append(Paragraph("Milestones", styles["SectionHeader"]))
        mtbl_data = [["Name", "Due Date", "Status"]]
        for m in milestones:
            mtbl_data.append([
                m.get("name") or "-",
                m.get("due_date") or "-",
                m.get("status") or "-",
            ])
        mt = Table(mtbl_data, repeatRows=1, colWidths=[None, 35 * mm, 30 * mm])
        mt.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                    ("BOX", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ]
            )
        )
        story.append(mt)
        story.append(Spacer(1, 12))

    # Analysis Summary and Key Findings
    if analysis.get("summary"):
        story.append(Paragraph("Analysis Summary", styles["SectionHeader"]))
        story.append(_p(analysis.get("summary", ""), styles["Normal"]))
        story.append(Spacer(1, 6))
    kf = analysis.get("key_findings") or []
    if kf:
        story.append(Paragraph("Key Findings", styles["Heading3"]))
        story.append(_bullet_list(kf, styles["Normal"]))
        story.append(Spacer(1, 12))

    # Metrics
    budget = metrics.get("budget", {})
    progress = metrics.get("progress", {})

    story.append(Paragraph("Metrics Overview", styles["SectionHeader"]))
    metrics_tbl = [
        ["Budget (Planned)", format_currency(budget.get("planned"), budget.get("currency", "USD"))],
        ["Budget (Actual)", format_currency(budget.get("actual"), budget.get("currency", "USD"))],
        ["Progress", percent(progress.get("percent_complete"))],
    ]
    mt2 = Table(metrics_tbl, colWidths=[50 * mm, None])
    mt2.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("BOX", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )
    story.append(mt2)
    story.append(Spacer(1, 12))

    # Risks
    risks = metrics.get("risks") or []
    if risks:
        story.append(Paragraph("Risks", styles["SectionHeader"]))
        rtbl_data = [["Risk", "Level", "Mitigation"]]
        for r in risks:
            rtbl_data.append([
                r.get("name") or r.get("title") or "-",
                r.get("level") or r.get("severity") or "-",
                r.get("mitigation") or "-",
            ])
        rt = Table(rtbl_data, repeatRows=1, colWidths=[50 * mm, 25 * mm, None])
        rt.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                    ("BOX", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ]
            )
        )
        story.append(rt)
        story.append(Spacer(1, 12))

    # Issues
    issues = metrics.get("issues") or []
    if issues:
        story.append(Paragraph("Issues", styles["SectionHeader"]))
        itbl_data = [["Issue", "Status", "Owner"]]
        for i in issues:
            itbl_data.append([
                i.get("name") or i.get("title") or "-",
                i.get("status") or "-",
                i.get("owner") or "-",
            ])
        it = Table(itbl_data, repeatRows=1, colWidths=[None, 25 * mm, 35 * mm])
        it.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                    ("BOX", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ]
            )
        )
        story.append(it)
        story.append(Spacer(1, 12))

    # Recommendations
    recs = analysis.get("recommendations") or []
    if recs:
        story.append(Paragraph("Recommendations", styles["SectionHeader"]))
        story.append(_bullet_list(recs, styles["Normal"]))
        story.append(Spacer(1, 12))

    # Build
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf.getvalue()

