import io
from datetime import datetime
from zipfile import ZipFile, ZIP_DEFLATED


MIT_LICENSE = """MIT License

Copyright (c) {year} {author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

APACHE2_LICENSE = """Apache License 2.0

Copyright (c) {year} {author}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


def _yaml_escape(value: str) -> str:
    if value is None:
        return "''"
    v = str(value)
    if any(c in v for c in [":", "-", "#", "\n", "\"", "'"]) or v.strip() != v:
        v = v.replace("\n", "\\n").replace("\"", "\\\"")
        return f'"{v}"'
    return v


def _parse_dependencies(dep_str: str):
    deps = []
    if dep_str:
        for raw in dep_str.replace("\n", ",").split(","):
            d = raw.strip()
            if d:
                deps.append(d)
    return deps


def _parse_env_vars(env_text: str):
    envs = []
    if not env_text:
        return envs
    for line in env_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, val = line.split("=", 1)
            envs.append((key.strip(), val.strip()))
        else:
            envs.append((line, ""))
    return envs


def _manifest_yaml(ctx):
    services = ctx.get("services") or {}
    now = datetime.utcnow().isoformat() + "Z"
    lines = [
        f"schemaVersion: 1",
        f"name: {_yaml_escape(ctx['project_name'])}",
        f"slug: {_yaml_escape(ctx['slug'])}",
        f"description: {_yaml_escape(ctx['description'])}",
        f"author: {_yaml_escape(ctx['author'])}",
        f"license: {_yaml_escape(ctx['license'])}",
        f"language: python",
        f"framework: flask",
        f"python: {_yaml_escape(ctx['python_version'])}",
        f"ci: {_yaml_escape(ctx['ci_provider'])}",
        f"createdAt: {_yaml_escape(now)}",
        f"includeDocker: {str(bool(ctx['include_docker'])).lower()}",
        f"includeTests: {str(bool(ctx['include_tests'])).lower()}",
        f"services:",
        f"  postgres: {str(bool(services.get('postgres'))).lower()}",
        f"  redis: {str(bool(services.get('redis'))).lower()}",
        f"dependencies:",
    ]
    for d in _parse_dependencies(ctx.get("dependencies") or ""):
        lines.append(f"  - {_yaml_escape(d)}")
    envs = _parse_env_vars(ctx.get("env_vars") or "")
    if envs:
        lines.append("env:")
        for k, v in envs:
            safe_v = v if v else ""  # do not leak secrets
            lines.append(f"  {k}: {_yaml_escape(safe_v)}")
    return "\n".join(lines) + "\n"


def _readme_md(ctx):
    services = ctx.get("services") or {}
    deps = _parse_dependencies(ctx.get("dependencies") or "")
    envs = _parse_env_vars(ctx.get("env_vars") or "")
    ci = ctx.get("ci_provider")
    lines = [
        f"# {ctx['project_name']}",
        "",
        ctx.get("description") or "A Flask project generated by the Idea-to-Project wizard.",
        "",
        "## Stack",
        "- Python",
        "- Flask",
        f"- CI: {ci}",
    ]
    if services.get("postgres"):
        lines.append("- PostgreSQL")
    if services.get("redis"):
        lines.append("- Redis")
    lines += [
        "",
        "## Getting Started",
        "- Create and activate a virtual environment",
        "- Install dependencies: `pip install -r requirements.txt`",
    ]
    if ctx.get("include_tests"):
        lines.append("- Dev deps: `pip install -r requirements-dev.txt`")
    lines += [
        "- Run app: `make run` (or `python run.py`)",
        "",
        "## Environment",
        "Copy `.env.example` to `.env` and fill values.",
        "",
        "## Makefile targets",
        "- install, install-dev, run, lint, test",
        "",
        "## Generated",
        "- manifest.yaml",
        "- CI workflow",
        "- Dockerfile and docker-compose (if selected)",
    ]
    if deps:
        lines += ["", "## Declared dependencies"]
        for d in deps:
            lines.append(f"- {d}")
    if envs:
        lines += ["", "## Environment variables"]
        for k, _ in envs:
            lines.append(f"- {k}")
    return "\n".join(lines) + "\n"


def _gitignore():
    return """# Python
__pycache__/
*.py[cod]
*.egg-info/
.venv/
venv/
.env
.env.*

# Byte-compiled / optimized / DLL files
*.pyd
*.pyo

# Distribution / packaging
build/
dist/
.eggs/

# VSCode
.vscode/

# macOS
.DS_Store

# Coverage
.coverage
htmlcov/

# Pytest
.pytest_cache/

# Docker
*.log
*.pid

# Pipenv/Poetry
Pipfile
Pipfile.lock
poetry.lock
"""


def _requirements(ctx):
    base = [
        "Flask>=2.3,<4.0",
        "python-dotenv>=0.21",
    ]
    services = ctx.get("services") or {}
    if services.get("postgres"):
        base.append("psycopg2-binary>=2.9")
    if services.get("redis"):
        base.append("redis>=4.5")
    for d in _parse_dependencies(ctx.get("dependencies") or ""):
        if d not in base:
            base.append(d)
    return "\n".join(base) + "\n"


def _requirements_dev(ctx):
    if not ctx.get("include_tests"):
        return ""
    dev = [
        "pytest>=7.4",
        "pytest-cov>=4.1",
        "flake8>=6.1",
        "black>=23.7",
    ]
    return "\n".join(dev) + "\n"


def _flake8_cfg():
    return """[flake8]
max-line-length = 100
ignore = E203, W503
exclude = .git,__pycache__,build,dist,venv,.venv
"""


def _pyproject_toml():
    return """[tool.black]
line-length = 100
target-version = ["py311", "py310"]
"""


def _makefile(ctx):
    return f"""PYTHON ?= python3
PIP ?= pip

install:
\t$(PIP) install -r requirements.txt

install-dev: install
\t$(PIP) install -r requirements-dev.txt

lint:
\tflake8 src {ctx['package_name']} tests || true
\tblack --check src tests || true

test:
\tpytest -q --maxfail=1 --disable-warnings

run:
\t$(PYTHON) run.py

.PHONY: install install-dev lint test run
"""


def _app_init(ctx):
    return f"""from flask import Flask
from dotenv import load_dotenv
import os

load_dotenv()


def create_app():
    app = Flask(__name__)
    app.config['ENV'] = os.getenv('FLASK_ENV', 'production')
    app.config['DEBUG'] = os.getenv('FLASK_DEBUG', '0') == '1'

    from .routes import bp as routes_bp
    app.register_blueprint(routes_bp)

    return app
"""


def _app_routes(ctx):
    return """from flask import Blueprint, jsonify

bp = Blueprint('routes', __name__)

@bp.get('/')
def hello():
    return jsonify({
        'message': 'Hello from your new Flask app!',
        'status': 'ok'
    })
"""


def _wsgi(ctx):
    return """from src.app import create_app
app = create_app()
"""


def _run_py(ctx):
    return """from src.app import create_app

app = create_app()

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True)
"""


def _test_sample(ctx):
    return """from src.app import create_app

def test_root_ok():
    app = create_app()
    client = app.test_client()
    rv = client.get('/')
    assert rv.status_code == 200
    data = rv.get_json()
    assert data['status'] == 'ok'
"""


def _dockerfile(ctx):
    py = ctx.get("python_version") or "3.11"
    return f"""# syntax=docker/dockerfile:1
FROM python:{py}-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt || true

COPY . .

EXPOSE 8000
CMD ["python", "run.py"]
"""


def _compose_yaml(ctx):
    services = ctx.get("services") or {}
    lines = [
        "version: '3.9'",
        "services:",
        "  app:",
        "    build: .",
        "    ports:",
        "      - '8000:8000'",
        "    env_file:",
        "      - .env",
        "    volumes:",
        "      - ./:/app",
    ]
    depends = []
    if services.get("postgres"):
        depends.append("db")
    if services.get("redis"):
        depends.append("redis")
    if depends:
        lines.append("    depends_on:")
        for d in depends:
            lines.append(f"      - {d}")
    if services.get("postgres"):
        lines += [
            "  db:",
            "    image: postgres:15",
            "    environment:",
            "      POSTGRES_DB: appdb",
            "      POSTGRES_USER: app",
            "      POSTGRES_PASSWORD: app",
            "    ports:",
            "      - '5432:5432'",
            "    volumes:",
            "      - pgdata:/var/lib/postgresql/data",
        ]
    if services.get("redis"):
        lines += [
            "  redis:",
            "    image: redis:7",
            "    ports:",
            "      - '6379:6379'",
        ]
    if services.get("postgres"):
        lines += [
            "volumes:",
            "  pgdata:",
        ]
    return "\n".join(lines) + "\n"


def _env_example(ctx):
    envs = _parse_env_vars(ctx.get("env_vars") or "")
    base = [
        "FLASK_ENV=development",
        "FLASK_DEBUG=1",
    ]
    for k, v in envs:
        if not any(line.startswith(f"{k}=") for line in base):
            base.append(f"{k}={v}")
    return "\n".join(base) + "\n"


def _github_actions_yaml(ctx):
    py = ctx.get("python_version") or "3.11"
    return f"""name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '{py}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Lint
        run: |
          if [ -f requirements-dev.txt ]; then \
            flake8 src tests || true; \
            black --check src tests || true; \
          fi
      - name: Test
        run: |
          if [ -f requirements-dev.txt ]; then pytest -q --maxfail=1 --disable-warnings; fi
"""


def _gitlab_ci_yaml(ctx):
    py = ctx.get("python_version") or "3.11"
    return f"""image: python:{py}

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

test:
  stage: test
  script:
    - if [ -f requirements-dev.txt ]; then flake8 src tests || true; fi
    - if [ -f requirements-dev.txt ]; then black --check src tests || true; fi
    - if [ -f requirements-dev.txt ]; then pytest -q --maxfail=1 --disable-warnings; fi
"""


def _license(ctx):
    license_kind = (ctx.get("license") or "").strip().lower()
    year = datetime.utcnow().year
    author = ctx.get("author") or ""
    if license_kind in ("mit", "mit license", "mit-0"):
        return MIT_LICENSE.format(year=year, author=author)
    if license_kind in ("apache", "apache-2.0", "apache license 2.0"):
        return APACHE2_LICENSE.format(year=year, author=author)
    return ""  # No license


def generate_project_zip(ctx: dict) -> io.BytesIO:
    slug = ctx["slug"]
    pkg = ctx["package_name"]
    include_tests = bool(ctx.get("include_tests", True))
    include_docker = bool(ctx.get("include_docker", True))
    ci = (ctx.get("ci_provider") or "github").lower()

    buf = io.BytesIO()
    with ZipFile(buf, "w", ZIP_DEFLATED) as z:
        root = slug
        # Core files
        z.writestr(f"{root}/README.md", _readme_md(ctx))
        z.writestr(f"{root}/manifest.yaml", _manifest_yaml(ctx))
        z.writestr(f"{root}/.gitignore", _gitignore())
        lic = _license(ctx)
        if lic:
            z.writestr(f"{root}/LICENSE", lic)
        z.writestr(f"{root}/requirements.txt", _requirements(ctx))
        if include_tests:
            z.writestr(f"{root}/requirements-dev.txt", _requirements_dev(ctx))
            z.writestr(f"{root}/.flake8", _flake8_cfg())
            z.writestr(f"{root}/pyproject.toml", _pyproject_toml())
        z.writestr(f"{root}/Makefile", _makefile(ctx))
        z.writestr(f"{root}/.env.example", _env_example(ctx))

        # Source structure
        z.writestr(f"{root}/src/__init__.py", "# src package\n")
        z.writestr(f"{root}/src/app/__init__.py", _app_init(ctx))
        z.writestr(f"{root}/src/app/routes.py", _app_routes(ctx))
        z.writestr(f"{root}/wsgi.py", _wsgi(ctx))
        z.writestr(f"{root}/run.py", _run_py(ctx))

        # Tests
        if include_tests:
            z.writestr(f"{root}/tests/test_app.py", _test_sample(ctx))

        # Docker artifacts
        if include_docker or any(ctx.get("services", {}).values()):
            z.writestr(f"{root}/Dockerfile", _dockerfile(ctx))
            z.writestr(f"{root}/docker-compose.yml", _compose_yaml(ctx))

        # CI
        if ci == "github":
            z.writestr(f"{root}/.github/workflows/ci.yml", _github_actions_yaml(ctx))
        elif ci == "gitlab":
            z.writestr(f"{root}/.gitlab-ci.yml", _gitlab_ci_yaml(ctx))
        # none -> skip

    buf.seek(0)
    return buf

