#!/usr/bin/env python3
"""
Auto-generate basic pytest route tests from a Flask app.

Usage:
  python tools/generate_tests.py
This will write tests/generated/test_routes_generated.py
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict

from app import create_app

OUTPUT_PATH = Path("tests/generated/test_routes_generated.py")
HEADER = """# This file is auto-generated by tools/generate_tests.py
# Do not edit manually. Regenerate via: python tools/generate_tests.py

"""

SKIP_ENDPOINTS = {"static"}
SKIP_METHODS = {"HEAD", "OPTIONS"}


def sample_value_for_converter(converter_name: str):
    name = (converter_name or "").lower()
    if "int" in name:
        return 1
    if "float" in name or "decimal" in name:
        return 1.0
    if "uuid" in name:
        return "123e4567-e89b-12d3-a456-426614174000"
    if "path" in name:
        return "a/b/c"
    return "test"


def build_path_with_samples(rule) -> str:
    path = rule.rule
    arguments = getattr(rule, "arguments", set()) or set()
    converters: Dict[str, object] = getattr(rule, "_converters", {}) or {}
    def repl(match):
        name = match.group(1)
        conv = converters.get(name)
        conv_name = getattr(conv, "__class__", type(conv)).__name__ if conv else ""
        val = sample_value_for_converter(conv_name)
        return str(val)
    # replace <converter:name> or <name>
    pattern = re.compile(r"<(?:(?:[^:>]+):)?([^>]+)>")
    return pattern.sub(repl, path)


def generate_tests():
    app = create_app(testing=True)
    client_fixture = "client"
    lines = [HEADER]

    # Stable order
    rules = sorted(app.url_map.iter_rules(), key=lambda r: r.rule)

    for rule in rules:
        if rule.endpoint in SKIP_ENDPOINTS:
            continue
        methods = sorted((rule.methods or set()) - SKIP_METHODS)
        if not methods:
            continue
        path = build_path_with_samples(rule)
        safe_name = (
            rule.rule.strip("/").replace("/", "_").replace("<", "").replace(">", "").replace(":", "_")
            or "root"
        )
        for m in methods:
            m_lower = m.lower()
            func_name = f"test_{m_lower}_{safe_name}"
            lines.append(f"def {func_name}({client_fixture}):")
            if m.upper() in {"POST", "PUT", "PATCH"}:
                lines.append("    payload = {\"example\": \"data\"}")
                lines.append(f"    resp = {client_fixture}.{m_lower}(\"{path}\", json=payload)")
            else:
                lines.append(f"    resp = {client_fixture}.{m_lower}(\"{path}\")")
            lines.append("    assert resp.status_code == 200\n")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    return OUTPUT_PATH


if __name__ == "__main__":
    out = generate_tests()
    print(f"Wrote {out}")

